name: "Test"
on:
  push:
    branches-ignore:
      - 'dependabot/*'
  schedule:
    - cron: '22 22 * * 5'
env:
  IMAGE: ${{ github.repository }}

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: actionshub/markdownlint@v1.0.0

      - name: YAML Lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: .yamllint.yaml
          yamllint_file_or_dir: action.yml

      - name: Dockerfile Lint
        uses: burdzwastaken/hadolint-action@1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${IMAGE}:test .

    - name: Run container-structure-test tests
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
        container-structure-test test --image ${IMAGE}:test --config tests/structure_test.yaml

    - name: Install bats
      run: sudo apt-get -y install bats > /dev/null

    - name: Run CI script
      run: ./tests/run.bats
